---
- name: Enable Apache common modules
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods }}"
  notify: restart apache

- name: Enable Apache gismap modules
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_gismap }}"
  notify: restart apache

- name: Apache Modules config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
    owner: www-data
    group: www-data
    mode: 0644
  with_items:
      - { src: 'mapcache.j2', dest: '/etc/apache2/mods-available/mapcache.conf' }
      - { src: 'tile.j2', dest: '/etc/apache2/mods-available/tile.conf' }
  notify: restart apache
  when: apache_create_vhosts

- name: Add Modules symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
      - { src: '/etc/apache2/mods-available/mapcache.conf', dest: '/etc/apache2/mods-enabled/mapcache.conf' }
      - { src: '/etc/apache2/mods-available/tile.conf', dest: '/etc/apache2/mods-enabled/tile.conf' }
  notify: restart apache
  when: apache_create_vhosts

- name: Apache Hosts config
  template:
    src: "hosts.j2"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts

- name: Add Hosts symlink
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: restart apache
  when: apache_create_vhosts

